site_name: My Docs
nav:
    - Home: 'index.md'
    - 'Workouts':
        - 'No equipment': 'workouts/no-equipment.md'
        - 'with furniture and stuff': 'workouts/with-furniture-and-stuff.md'
    - 'Food': 
        - 'Meals': 'food/meals.md'