site_name: Active Living
theme:
  name: material
nav:
    - Home: 'index.md'
    - 'Workouts':
        - 'No equipment': 'workouts/no-equipment.md'
        - 'with furniture and stuff': 'workouts/with-furniture-and-stuff.md'
    - 'Food': 
        - 'Meals': 'food/meals.md'
        - 'Salads': 'food/salads.md'
        - 'Dips': 'food/dips.md'
        - 'Spice Mixes': 'food/spice-mixes.md'